### ISSUE TITLE
Documentation as Markdown

### ISSUE THREAD

**Issue by DaEgi01** [pcfantasy/RealCity#1]
Wanted to check out your mod, but only found the documentation in docx format which is a shame.
It would be awesome if you'd use markdown, so that one could directly read it on github.

**Comment by pcfantasy** [comment]
I will update document these few days with a lot of update, and I will update document link after I finish them.

**Comment by pcfantasy** [comment]
Need to update doc to markdown when I have time

**Comment by pcfantasy** [comment]
@DaEgi01 
Done finally.
Thanks for your advance 2 years ago :)
https://github.com/pcfantasy/RealCity/wiki

**Comment by DaEgi01** [comment]
awesome thx :)
