### ISSUE TITLE
Info view.

### ISSUE THREAD

**Issue by itsumo2009** [pcfantasy/RealCity#13]
I have some ideas about info view.
1. Money info view.
2. Money flow info view.
3. Working places and workers.
4. Working transportation info view.

Have you any other ideas about info view.

**Comment by pcfantasy** [comment]
1. Is it what you have done in landprice info view?
2.3.4 Can you explain you idea?

**Comment by itsumo2009** [comment]
2. It shows level of salaries for residental and how offten comercial and industrial have negative money.
3. It shows how many adults don't have workplace for residental, and how many industrial and commercial buildings have vacancies.
4. It show if selected commercial and industrial building where do workers residental place.

**Comment by itsumo2009** [comment]
1. Yes. But I haven't finished it yet.
I haven't desided what formula should be for industrial building.

**Comment by pcfantasy** [comment]
I think it is better to make a seperate mod for 3&4, I can add this mod to RealCity Bestlist to work better with RealCity Mod.

For 2, It is similar as 1, you can help add this to another infoview.

BTW, what`s your steamID, I want to release new version and mention about you. And if you have time to work with this project in the futher. I can add you as a founder in steam page.

**Comment by itsumo2009** [comment]
My profile is https://steamcommunity.com/profiles/76561198012629319/

**Comment by itsumo2009** [comment]
What is the best formula for economic view for commercial and industrial?
I think it's should be formula like "I see red industrial, I make better situation for it, I see green industrial".
But I see green industrial very seldom.

**Comment by pcfantasy** [comment]
@itsumo2009 

When industrial building have money, they will send all the money to employ and to a vitural boss (in certain time). 
So for  industrial building, it is hard to save money. They can only earn money by sell production. But cargotruck need certain time to finish transition. When cargotruck is not going back, building can not sell another production(each building have their max cargotruck count.) So, industrial building will get a huge money, then spend them and after a while, get another huge money....

For commercial, for most of time, they are always being visited, so the situation will be more smooth than industrial building.

**Comment by itsumo2009** [comment]
Then Shall I split one view into two.
For residental and industrial.

**Comment by itsumo2009** [comment]
Can you make special movable panel for real city button?
They don't save their placement after load.

**Comment by pcfantasy** [comment]
@itsumo2009 

You can change infoview.

For real city button, I can save their placement, I will try to update this when I have time.

**Comment by pcfantasy** [comment]
@itsumo2009  
I have create a new issue about save button placement after load.
#18 

I will now pay high priority on #1 , since this mod is very stable now.

Please help on #13 #17 , thanks a lot.

**Comment by pcfantasy** [comment]
@itsumo2009 

I see there is a imbalanced point.  industrial and commerical building spend their money to employee and boss too quickly.

So I will simplify salary logic, all the I&C building will give 5% of their money to employ in every refresh priod.

After this update, you will not see green industrial very seldom. And those red industrial is really in bad situation, should make better situation for it.

**Comment by itsumo2009** [comment]
What's about initial family money?
May be it should be greater than zero?
What's about 5d5000?

**Comment by pcfantasy** [comment]
@itsumo2009 
I try to add this before. But then you can cheat for money, you can try to collect all the money from citizen and then produce problem on residential building to let those citizens leave, then let another citizens moving in.
