### ISSUE TITLE
Vehicle not found + ScriptableObject.CreateInstance

### ISSUE THREAD

**Issue by gatepoet** [pcfantasy/RealCity#2]
I get a lot of these error massages. Don't know if they are related, but it seems that one or both causes the game to freeze after a while.

> ItemClass must be instantiated using the ScriptableObject.CreateInstance method instead of new ItemClass.
>  
> (Filename:  Line: 598)

> Vehicle not found!
>    at System.Environment.get_StackTrace()
>    at Building.RemoveGuestVehicle(UInt16 vehicleID, Vehicle ByRef data)
>    at FuelAlarm.CustomCargoTruckAI.RemoveTarget(UInt16 vehicleID, Vehicle ByRef data)
>    at FuelAlarm.CustomCargoTruckAI.SetTarget(UInt16 vehicleID, Vehicle ByRef data, UInt16 targetBuilding)
>    at RealCity.RealCityCargoTruckAI.ArriveAtTarget(UInt16 vehicleID, Vehicle ByRef data)
>    at CargoTruckAI.ArriveAtDestination(UInt16 vehicleID, Vehicle ByRef vehicleData)
>    at CarAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, Frame ByRef frameData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
>    at VehicleAI.SimulationStep(UInt16 vehicleID, Vehicle ByRef vehicleData, UInt16 leaderID, Vehicle ByRef leaderData, Int32 lodPhysics)
>    at TrafficManager.Custom.AI.CustomCarAI.CustomSimulationStep(UInt16 vehicleId, Vehicle ByRef vehicleData, Vector3 physicsLodRefPos)
>    at TrafficManager.Custom.AI.CustomCargoTruckAI.CustomSimulationStep(UInt16 vehicleId, Vehicle ByRef vehicleData, Vector3 physicsLodRefPos)
>    at VehicleManager.SimulationStepImpl(Int32 subStep)
>    at SimulationManagerBase`2.SimulationStep(Int32 subStep)
>    at VehicleManager.ISimulationManager.SimulationStep(Int32 subStep)
>    at SimulationManager.SimulationStep()
>    at SimulationManager.SimulationThread()  [Core]

**Comment by pcfantasy** [comment]
Thanks for the feedback.

1. For Vehicle not found! I have fixed this issue in new release version of RealGasStation Mod.
Please update this Mod and Use TMPE to remove all vehicle.
Please feedback to me whether there is two dll inside
F:\SteamLibrary\steamapps\workshop\content\255710\1623509958

2. For ItemClass must be instantiated using the ScriptableObject.CreateInstance method instead of new ItemClass. 
Can you unsub my mod and check if it is still exist?

**Comment by pcfantasy** [comment]
@gatepoet

I fix 2

For 1, Please give me feedback，thanks

**Comment by pcfantasy** [comment]
Fixed now.
