### ISSUE TITLE
City Resource Building - Showing 0 Trucks in Use

### ISSUE THREAD

**Issue by SoRobby** [pcfantasy/RealCity#26]
Probably a known bug or issue - the City Resource Building is display 0/0 maintenance trucks in use.

The text "Maintenance trucks in use: 0/0" always says 0 trucks in use even if a truck is active.

Ideas
- Would it be possible to change the text to say "Number of Resource trucks in use: "?
- Add the ability to increase the number of trucks per City Resource Building.
- Add another asset called Large City Resource Building that holds more resources and has more trucks.

![](https://i.imgur.com/GxH6bhX.png)

**Comment by pcfantasy** [comment]
This what real construction mod does
