### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by balag12** [pcfantasy/RealCity#3]
I believe it would be more realistic for the "Parliament" to be renamed to a **Council** or **Assembly**.

Parliaments are almost always national level bodies, and a city would not have such a body named in that way.

**Comment by pcfantasy** [comment]
@balag12 

#4  will work with this issue.

Then can you help create pull request to update en.txt for better translation?

**Comment by balag12** [comment]
Let me know when you have brought in support for translations per #4 and I will have a go at it.

**Comment by pcfantasy** [comment]
@balag12 

You can help optimze english translation now

https://github.com/pcfantasy/RealCity/blob/master/Locales/en.txt

**Comment by balag12** [comment]
Can the names have spaces? Or do they need to be in camel case?

**Comment by balag12** [comment]
#9

**Comment by pcfantasy** [comment]
> Can the names have spaces? Or do they need to be in camel case?

They can have space.
