### ISSUE TITLE
1893036262 Mayor's Dashboard v2

### ISSUE THREAD

**Issue by aubergine10** [pcfantasy/RealCity#33]
The mod `Mayor's Dashboard v2` includes the code from `Export Electricity` mod and is likely incompatible.

```cs
{ 1893036262uL, Status.MinorIssues  }, // Mayor's Dashboard v2 (includes code from Export Electricity)
```

**Comment by pcfantasy** [comment]
@aubergine10  

Ok, I will add this in my incompatible list.

Actually, the conflict bettween RealCity and Export Electricity is not technical. Export Electricity can work with RealCity to run the game, but it will break the economic balance of the whole system.

Thanks for your remind.
