### ISSUE TITLE
No parking cars

### ISSUE THREAD

**Issue by flexodood** [pcfantasy/RealCity#38]
Hi.
I love your work.
Sadly it seems to despawn all parked cars lately?
Only other mods active where "TMPE" and "Real time".

**Comment by flexodood** [comment]
Just tried; No Mods. only Harmony2044 and Real city. No parking cars.

**Comment by flexodood** [comment]
Omg my bad. Poor people don't use cars. This mod is so amazing. Never noticed it when starting a City.

keep up the great work

**Comment by pcfantasy** [comment]
@flexodood  if you do not want this feature, try to disable Citizen will not use passenger car if they do not have enough money in mod`s option.
