### ISSUE TITLE
License File Needed

### ISSUE THREAD

**Issue by balag12** [pcfantasy/RealCity#6]
Please add a license file, so as to clarify what the code is available for.

https://choosealicense.com/

**Comment by pcfantasy** [comment]
OK, after I make some important updates.

#4  #5

**Comment by balag12** [comment]
I would argue that it is best to do it _before_ you issue those updates - it will allow potential contributors, such as myself, to contribute according to the license provided.

If you indicate which license you prefer, I can make a pull request to add one.

**Comment by pcfantasy** [comment]
@balag12 

Pull MIT license to me please.

**Comment by balag12** [comment]
#7

**Comment by balag12** [comment]
Closed.
